In [87]:
#Import des libraries necessaires
from skimage import io, novice

from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn import tree

from sklearn.metrics import accuracy_score, confusion_matrix

import numpy as np


# Creation de nos arbres de decision en utilisant l'entropie et un max_depth variable
desTree1 = tree.DecisionTreeClassifier(criterion='entropy')
desTree2 = tree.DecisionTreeClassifier(criterion='entropy', max_depth=2)
desTree3 = tree.DecisionTreeClassifier(criterion='entropy', max_depth=3)
desTree4 = tree.DecisionTreeClassifier(criterion='entropy', max_depth=4)
desTree5 = tree.DecisionTreeClassifier(criterion='entropy', max_depth=5)
desTree6 = tree.DecisionTreeClassifier(criterion='entropy', max_depth=10)

destrees = []
destrees.append({'tree': desTree1, 
                'label': "Arbe de décision max_depth = None"})
destrees.append({'tree': desTree2, 
                'label': "Arbe de décision max_depth = 2"})
destrees.append({'tree': desTree3, 
                'label': "Arbe de décision max_depth = 3"})
destrees.append({'tree': desTree4, 
                'label': "Arbe de décision max_depth = 4"})
destrees.append({'tree': desTree5, 
                'label': "Arbe de décision max_depth = 5"})
destrees.append({'tree': desTree6, 
                'label': "Arbe de décision max_depth = 10"})

# Chargement des donnees
iris = load_iris()

for element in destrees:
    # Apprentissage avec la fonction train
    # iris.data[:, :3] veut dire qu'on utilise la totalite des "rows" et seulement 3 colonnes [:, 3]
    # pour utiliser seulement 3 "rows" et la totalite des colonnes on utilise [:3, :]
    element['tree'] = element['tree'].fit(iris.data[:, :3], iris.target)

    #CrossVal Score
    print("CrossVal Score de :" + element['label'])
    print(cross_val_score(element['tree'], iris.data[:, :3], iris.target, cv=5))
    print('\n')




CrossVal Score de :Arbe de décision max_depth = None
[0.93333333 0.96666667 0.86666667 0.93333333 0.86666667]


CrossVal Score de :Arbe de décision max_depth = 2
[0.93333333 1.         0.86666667 0.93333333 1.        ]


CrossVal Score de :Arbe de décision max_depth = 3
[0.93333333 1.         0.86666667 0.93333333 1.        ]


CrossVal Score de :Arbe de décision max_depth = 4
[0.93333333 1.         0.86666667 0.93333333 0.93333333]


CrossVal Score de :Arbe de décision max_depth = 5
[0.96666667 0.96666667 0.86666667 0.93333333 0.93333333]


CrossVal Score de :Arbe de décision max_depth = 10
[0.96666667 0.96666667 0.86666667 0.93333333 0.9       ]


